import * as Viewer from '../viewer';
import { GfxDevice } from '../gfx/platform/GfxPlatform';
import { SceneContext } from '../SceneBase';
import { SilentHill3Renderer, SilentHill3TextureHolder } from './render';
import { SilentHill3MapParser } from './map';
import { NamedArrayBufferSlice } from '../DataFetcher';

const pathBase = 'SilentHill3';
class SilentHill3SceneDesc implements Viewer.SceneDesc {
    constructor(public id: string, private chapter: string, private areaCode: string, private roomCode: string, public name: string = id, public hasTr?: boolean) {}

    public async createScene(device: GfxDevice, context: SceneContext): Promise<Viewer.SceneGfx> {
        const mapData = await context.dataFetcher.fetchData(
            `${pathBase}/${this.chapter}/${this.areaCode}${this.roomCode}/${this.id}.map`);
        const texGbData = await context.dataFetcher.fetchData(
            `${pathBase}/${this.chapter}/${this.areaCode}GB/${this.areaCode}GB.tex`);
        let texTrData: NamedArrayBufferSlice | undefined;
        if (this.hasTr) {
            texTrData = await context.dataFetcher.fetchData(
                `${pathBase}/${this.chapter}/${this.areaCode}${this.roomCode}/${this.id}TR.tex`);
        }

        const parser = new SilentHill3MapParser;
        const map = parser.parseMap(mapData, texGbData, texTrData);

        const textureHolder = new SilentHill3TextureHolder;
        textureHolder.addMapTextures(device, map);

        return new SilentHill3Renderer(device, map, textureHolder);
    }
}

const id = 'SilentHill3';
const name = 'Silent Hill 3';
const sceneDescs = [
    "Central Square Shopping Mall - 1F",
    new SilentHill3SceneDesc("mr1f", "X0", "MR", "1F", "mr1f"),
    new SilentHill3SceneDesc("mr2e", "X0", "MR", "1F", "mr2e"),
    new SilentHill3SceneDesc("mr2f", "X0", "MR", "1F", "mr2f", /*hasTr=*/true),
    new SilentHill3SceneDesc("mrdf", "X0", "MR", "1F", "mrdf"),
    new SilentHill3SceneDesc("mre1", "X0", "MR", "1F", "mre1"),
    new SilentHill3SceneDesc("mree", "X0", "MR", "1F", "mree", /*hasTr=*/true),
    new SilentHill3SceneDesc("mref", "X0", "MR", "1F", "mref", /*hasTr=*/true),
    new SilentHill3SceneDesc("mrfd", "X0", "MR", "1F", "mrfd", /*hasTr=*/true),
    new SilentHill3SceneDesc("mrfe", "X0", "MR", "1F", "mrfe", /*hasTr=*/true),
    new SilentHill3SceneDesc("mrff", "X0", "MR", "1F", "mrff"),
    "Central Square Shopping Mall - 2F",
    new SilentHill3SceneDesc("mr1e", "X0", "MR", "2F", "mr1e", /*hasTr=*/true),
    new SilentHill3SceneDesc("mr11", "X0", "MR", "2F", "mr11", /*hasTr=*/true),
    new SilentHill3SceneDesc("mr12", "X0", "MR", "2F", "mr12"),
    new SilentHill3SceneDesc("mr21", "X0", "MR", "2F", "mr21", /*hasTr=*/true),
    new SilentHill3SceneDesc("mr22", "X0", "MR", "2F", "mr22"),
    new SilentHill3SceneDesc("mrd1", "X0", "MR", "2F", "mrd1"),
    new SilentHill3SceneDesc("mre2", "X0", "MR", "2F", "mre2", /*hasTr=*/true),
    new SilentHill3SceneDesc("mrf1", "X0", "MR", "2F", "mrf1", /*hasTr=*/true),
    new SilentHill3SceneDesc("mrf2", "X0", "MR", "2F", "mrf2", /*hasTr=*/true),
    "Central Square Shopping Mall (Otherworld) - 1F",
    new SilentHill3SceneDesc("mu1d", "X0", "MU", "1F", "mu1d"),
    new SilentHill3SceneDesc("mu2d", "X0", "MU", "1F", "mu2d", /*hasTr=*/true),
    new SilentHill3SceneDesc("mu2e", "X0", "MU", "1F", "mu2e", /*hasTr=*/true),
    new SilentHill3SceneDesc("mudf", "X0", "MU", "1F", "mudf"),
    new SilentHill3SceneDesc("mue1", "X0", "MU", "1F", "mue1"),
    new SilentHill3SceneDesc("muee", "X0", "MU", "1F", "muee"),
    new SilentHill3SceneDesc("muef", "X0", "MU", "1F", "muef"),
    new SilentHill3SceneDesc("mufd", "X0", "MU", "1F", "mufd"),
    new SilentHill3SceneDesc("mufe", "X0", "MU", "1F", "mufe"),
    "Central Square Shopping Mall (Otherworld) - 2F",
    new SilentHill3SceneDesc("mu11", "X0", "MU", "2F", "mu11"),
    new SilentHill3SceneDesc("mu12", "X0", "MU", "2F", "mu12"),
    new SilentHill3SceneDesc("mu13", "X0", "MU", "2F", "mu13", /*hasTr=*/true),
    new SilentHill3SceneDesc("mu21", "X0", "MU", "2F", "mu21"),
    new SilentHill3SceneDesc("mu22", "X0", "MU", "2F", "mu22"),
    new SilentHill3SceneDesc("mu31", "X0", "MU", "2F", "mu31"),
    new SilentHill3SceneDesc("mu32", "X0", "MU", "2F", "mu32"),
    new SilentHill3SceneDesc("mud1", "X0", "MU", "2F", "mud1"),
    new SilentHill3SceneDesc("mue2", "X0", "MU", "2F", "mue2"),
    new SilentHill3SceneDesc("muf1", "X0", "MU", "2F", "muf1", /*hasTr=*/true),
    new SilentHill3SceneDesc("muf2", "X0", "MU", "2F", "muf2"),
    new SilentHill3SceneDesc("muf3", "X0", "MU", "2F", "muf3"),
    new SilentHill3SceneDesc("muff", "X0", "MU", "2F", "muff"),
    "Central Square Shopping Mall (Otherworld) - 3F",
    new SilentHill3SceneDesc("mu1e", "X0", "MU", "3F", "mu1e"),
    new SilentHill3SceneDesc("mu1f", "X0", "MU", "3F", "mu1f", /*hasTr=*/true),
    new SilentHill3SceneDesc("mu2f", "X0", "MU", "3F", "mu2f"),
    new SilentHill3SceneDesc("mu3f", "X0", "MU", "3F", "mu3f"),
    "Hazel Street Station - Subway Station",
    new SilentHill3SceneDesc("tr1e", "X0", "TR", "STA", "tr1e"),
    new SilentHill3SceneDesc("tr1f", "X0", "TR", "STA", "tr1f"),
    new SilentHill3SceneDesc("tr2e", "X0", "TR", "STA", "tr2e"),
    new SilentHill3SceneDesc("tr2f", "X0", "TR", "STA", "tr2f"),
    new SilentHill3SceneDesc("tr11", "X0", "TR", "STA", "tr11"),
    new SilentHill3SceneDesc("tr21", "X0", "TR", "STA", "tr21"),
    new SilentHill3SceneDesc("trf1", "X0", "TR", "STA", "trf1"),
    "Hazel Street Station - Subway Platform",
    new SilentHill3SceneDesc("tre1", "X0", "TR", "PLA", "tre1"),
    new SilentHill3SceneDesc("tre2", "X0", "TR", "PLA", "tre2"),
    new SilentHill3SceneDesc("tree", "X0", "TR", "PLA", "tree"),
    new SilentHill3SceneDesc("tref", "X0", "TR", "PLA", "tref"),
    new SilentHill3SceneDesc("trf2", "X0", "TR", "PLA", "trf2"),
    new SilentHill3SceneDesc("trfe", "X0", "TR", "PLA", "trfe"),
    new SilentHill3SceneDesc("trff", "X0", "TR", "PLA", "trff"),
    "Hazel Street Station - Subway Train",
    new SilentHill3SceneDesc("tr1d", "X0", "TR", "TRA", "tr1d"),
    new SilentHill3SceneDesc("tr3f", "X0", "TR", "TRA", "tr3f"),
    new SilentHill3SceneDesc("tr13", "X0", "TR", "TRA", "tr13"),
    new SilentHill3SceneDesc("tr31", "X0", "TR", "TRA", "tr31"),
    new SilentHill3SceneDesc("trd1", "X0", "TR", "TRA", "trd1"),
    new SilentHill3SceneDesc("trdd", "X0", "TR", "TRA", "trdd"),
    new SilentHill3SceneDesc("trdf", "X0", "TR", "TRA", "trdf"),
    new SilentHill3SceneDesc("trdf_03", "X0", "TR", "TRA", "trdf_03"),
    new SilentHill3SceneDesc("trf3", "X0", "TR", "TRA", "trf3"),
    new SilentHill3SceneDesc("trf3_01", "X0", "TR", "TRA", "trf3_01"),
    new SilentHill3SceneDesc("trfd", "X0", "TR", "TRA", "trfd"),
    "Underpass - Upper",
    new SilentHill3SceneDesc("us1e", "X0", "US", "UP", "us1e"),
    new SilentHill3SceneDesc("us1f", "X0", "US", "UP", "us1f"),
    new SilentHill3SceneDesc("us2e", "X0", "US", "UP", "us2e"),
    new SilentHill3SceneDesc("us2f", "X0", "US", "UP", "us2f"),
    new SilentHill3SceneDesc("us3e", "X0", "US", "UP", "us3e"),
    new SilentHill3SceneDesc("us3f", "X0", "US", "UP", "us3f"),
    new SilentHill3SceneDesc("us11", "X0", "US", "UP", "us11"),
    new SilentHill3SceneDesc("us21", "X0", "US", "UP", "us21"),
    new SilentHill3SceneDesc("us31", "X0", "US", "UP", "us31"),
    new SilentHill3SceneDesc("usde", "X0", "US", "UP", "usde"),
    new SilentHill3SceneDesc("use1", "X0", "US", "UP", "use1"),
    new SilentHill3SceneDesc("usee", "X0", "US", "UP", "usee"),
    new SilentHill3SceneDesc("usef", "X0", "US", "UP", "usef"),
    new SilentHill3SceneDesc("usf1", "X0", "US", "UP", "usf1", /*hasTr=*/true),
    new SilentHill3SceneDesc("usfe", "X0", "US", "UP", "usfe"),
    new SilentHill3SceneDesc("usff", "X0", "US", "UP", "usff"),
    "Underpass - Lower",
    new SilentHill3SceneDesc("us1d", "X0", "US", "LOW", "us1d"),
    new SilentHill3SceneDesc("us12", "X0", "US", "LOW", "us12"),
    new SilentHill3SceneDesc("us13", "X0", "US", "LOW", "us13"),
    new SilentHill3SceneDesc("us22", "X0", "US", "LOW", "us22"),
    new SilentHill3SceneDesc("us32", "X0", "US", "LOW", "us32"),
    new SilentHill3SceneDesc("usd1", "X0", "US", "LOW", "usd1"),
    new SilentHill3SceneDesc("usd2", "X0", "US", "LOW", "usd2"),
    new SilentHill3SceneDesc("usdf", "X0", "US", "LOW", "usdf"),
    new SilentHill3SceneDesc("use2", "X0", "US", "LOW", "use2"),
    new SilentHill3SceneDesc("usf2", "X0", "US", "LOW", "usf2"),
    new SilentHill3SceneDesc("usf3", "X0", "US", "LOW", "usf3"),
    new SilentHill3SceneDesc("usfd", "X0", "US", "LOW", "usfd"),
    "Construction Site",
    new SilentHill3SceneDesc("bc1f", "X1", "BC", "", "bc1f", /*hasTr=*/true),
    new SilentHill3SceneDesc("bc11", "X1", "BC", "", "bc11"),
    new SilentHill3SceneDesc("bc12", "X1", "BC", "", "bc12", /*hasTr=*/true),
    new SilentHill3SceneDesc("bcf1", "X1", "BC", "", "bcf1"),
    new SilentHill3SceneDesc("bcf2", "X1", "BC", "", "bcf2", /*hasTr=*/true),
    new SilentHill3SceneDesc("bcfe", "X1", "BC", "", "bcfe"),
    new SilentHill3SceneDesc("bcff", "X1", "BC", "", "bcff", /*hasTr=*/true),
    "Hilltop Center - 2F",
    new SilentHill3SceneDesc("bre1", "X1", "BR", "2F", "bre1", /*hasTr=*/true),
    new SilentHill3SceneDesc("brf1", "X1", "BR", "2F", "brf1"),
    new SilentHill3SceneDesc("brf2", "X1", "BR", "2F", "brf2"),
    new SilentHill3SceneDesc("brf3", "X1", "BR", "2F", "brf3"),
    "Hilltop Center - 3F",
    new SilentHill3SceneDesc("br11", "X1", "BR", "3F", "br11", /*hasTr=*/true),
    new SilentHill3SceneDesc("br12", "X1", "BR", "3F", "br12"),
    new SilentHill3SceneDesc("br13", "X1", "BR", "3F", "br13"),
    new SilentHill3SceneDesc("br21", "X1", "BR", "3F", "br21", /*hasTr=*/true),
    new SilentHill3SceneDesc("br22", "X1", "BR", "3F", "br22"),
    new SilentHill3SceneDesc("br23", "X1", "BR", "3F", "br23"),
    new SilentHill3SceneDesc("br31", "X1", "BR", "3F", "br31", /*hasTr=*/true),
    new SilentHill3SceneDesc("br32", "X1", "BR", "3F", "br32", /*hasTr=*/true),
    "Hilltop Center - 5F",
    new SilentHill3SceneDesc("br1d", "X1", "BR", "5F", "br1d", /*hasTr=*/true),
    new SilentHill3SceneDesc("br1e", "X1", "BR", "5F", "br1e"),
    new SilentHill3SceneDesc("br1f", "X1", "BR", "5F", "br1f", /*hasTr=*/true),
    new SilentHill3SceneDesc("br2e", "X1", "BR", "5F", "br2e"),
    new SilentHill3SceneDesc("br2f", "X1", "BR", "5F", "br2f", /*hasTr=*/true),
    new SilentHill3SceneDesc("br3e", "X1", "BR", "5F", "br3e"),
    new SilentHill3SceneDesc("br3f", "X1", "BR", "5F", "br3f"),
    new SilentHill3SceneDesc("brff", "X1", "BR", "5F", "brff", /*hasTr=*/true),
    "Hilltop Center (Otherworld) - 1F",
    new SilentHill3SceneDesc("buee", "X1", "BU", "1F", "buee", /*hasTr=*/true),
    new SilentHill3SceneDesc("buef", "X1", "BU", "1F", "buef"),
    new SilentHill3SceneDesc("bufe", "X1", "BU", "1F", "bufe", /*hasTr=*/true),
    new SilentHill3SceneDesc("buff", "X1", "BU", "1F", "buff", /*hasTr=*/true),
    "Hilltop Center (Otherworld) - 2F",
    new SilentHill3SceneDesc("bud1", "X1", "BU", "2F", "bud1", /*hasTr=*/true),
    new SilentHill3SceneDesc("bud2", "X1", "BU", "2F", "bud2", /*hasTr=*/true),
    new SilentHill3SceneDesc("bue1", "X1", "BU", "2F", "bue1", /*hasTr=*/true),
    new SilentHill3SceneDesc("bue2", "X1", "BU", "2F", "bue2"),
    new SilentHill3SceneDesc("buf1", "X1", "BU", "2F", "buf1", /*hasTr=*/true),
    new SilentHill3SceneDesc("buf2", "X1", "BU", "2F", "buf2"),
    "Hilltop Center (Otherworld) - 4F",
    new SilentHill3SceneDesc("bu11", "X1", "BU", "4F", "bu11", /*hasTr=*/true),
    new SilentHill3SceneDesc("bu12", "X1", "BU", "4F", "bu12", /*hasTr=*/true),
    new SilentHill3SceneDesc("bu21", "X1", "BU", "4F", "bu21"),
    new SilentHill3SceneDesc("bu22", "X1", "BU", "4F", "bu22"),
    new SilentHill3SceneDesc("bu23", "X1", "BU", "4F", "bu23", /*hasTr=*/true),
    new SilentHill3SceneDesc("bu31", "X1", "BU", "4F", "bu31"),
    "Hilltop Center (Otherworld) - 5F",
    new SilentHill3SceneDesc("bu1e", "X1", "BU", "5F", "bu1e"),
    new SilentHill3SceneDesc("bu1f", "X1", "BU", "5F", "bu1f"),
    new SilentHill3SceneDesc("bu2e", "X1", "BU", "5F", "bu2e"),
    new SilentHill3SceneDesc("bu2f", "X1", "BU", "5F", "bu2f"),
    new SilentHill3SceneDesc("bu3e", "X1", "BU", "5F", "bu3e", /*hasTr=*/true),
    new SilentHill3SceneDesc("budf", "X1", "BU", "5F", "budf"),
    "City",
    new SilentHill3SceneDesc("tgf1", "X1", "TG", "", "tgf1", /*hasTr=*/true),
    "Daisy Villa Apartments",
    new SilentHill3SceneDesc("am1e", "X1", "AM", "", "am1e", /*hasTr=*/true),
    new SilentHill3SceneDesc("am1f", "X1", "AM", "", "am1f", /*hasTr=*/true),
    new SilentHill3SceneDesc("am11", "X1", "AM", "", "am11", /*hasTr=*/true),
    new SilentHill3SceneDesc("amf1", "X1", "AM", "", "amf1"),
    new SilentHill3SceneDesc("amfe", "X1", "AM", "", "amfe"),
    new SilentHill3SceneDesc("amff", "X1", "AM", "", "amff", /*hasTr=*/true),
    "Douglas' Car",
    new SilentHill3SceneDesc("cmf1", "X1", "CM", "", "cmf1", /*hasTr=*/true),
    "Jacks Inn",
    new SilentHill3SceneDesc("ot1f", "X2", "OT", "", "ot1f"),
    "Silent Hill",
    new SilentHill3SceneDesc("cc09", "X3", "CC", "", "cc09"),
    new SilentHill3SceneDesc("cc10", "X3", "CC", "", "cc10", /*hasTr=*/true),
    new SilentHill3SceneDesc("cc19", "X3", "CC", "", "cc19"),
    new SilentHill3SceneDesc("cc20", "X3", "CC", "", "cc20", /*hasTr=*/true),
    new SilentHill3SceneDesc("cc29", "X3", "CC", "", "cc29"),
    new SilentHill3SceneDesc("cc30", "X3", "CC", "", "cc30"),
    new SilentHill3SceneDesc("cc35", "X3", "CC", "", "cc35"),
    new SilentHill3SceneDesc("cc36", "X3", "CC", "", "cc36"),
    new SilentHill3SceneDesc("cc41", "X3", "CC", "", "cc41"),
    new SilentHill3SceneDesc("cc42", "X3", "CC", "", "cc42"),
    new SilentHill3SceneDesc("cc43", "X3", "CC", "", "cc43"),
    new SilentHill3SceneDesc("cc44", "X3", "CC", "", "cc44", /*hasTr=*/true),
    new SilentHill3SceneDesc("cc45", "X3", "CC", "", "cc45"),
    new SilentHill3SceneDesc("cc46", "X3", "CC", "", "cc46"),
    new SilentHill3SceneDesc("cc48", "X3", "CC", "", "cc48"),
    new SilentHill3SceneDesc("cc49", "X3", "CC", "", "cc49"),
    new SilentHill3SceneDesc("cc50", "X3", "CC", "", "cc50"),
    new SilentHill3SceneDesc("cc51", "X3", "CC", "", "cc51"),
    new SilentHill3SceneDesc("cc52", "X3", "CC", "", "cc52"),
    new SilentHill3SceneDesc("cc53", "X3", "CC", "", "cc53", /*hasTr=*/true),
    new SilentHill3SceneDesc("cc54", "X3", "CC", "", "cc54", /*hasTr=*/true),
    new SilentHill3SceneDesc("cc56", "X3", "CC", "", "cc56"),
    new SilentHill3SceneDesc("cc57", "X3", "CC", "", "cc57"),
    "Heaven's Night",
    new SilentHill3SceneDesc("thf1", "X2", "TH", "", "thf1"),
    "Brookhaven Hospital - 1F",
    new SilentHill3SceneDesc("hpcc", "X2", "HP", "1F", "hpcc"),
    new SilentHill3SceneDesc("hpcd", "X2", "HP", "1F", "hpcd", /*hasTr=*/true),
    new SilentHill3SceneDesc("hpce", "X2", "HP", "1F", "hpce"),
    new SilentHill3SceneDesc("hpdd", "X2", "HP", "1F", "hpdd", /*hasTr=*/true),
    new SilentHill3SceneDesc("hpee", "X2", "HP", "1F", "hpee", /*hasTr=*/true),
    new SilentHill3SceneDesc("hpfe", "X2", "HP", "1F", "hpfe", /*hasTr=*/true),
    new SilentHill3SceneDesc("hpff", "X2", "HP", "1F", "hpff"),
    "Brookhaven Hospital - 2F",
    new SilentHill3SceneDesc("hpc3", "X2", "HP", "2F", "hpc3"),
    new SilentHill3SceneDesc("hpd1", "X2", "HP", "2F", "hpd1"),
    new SilentHill3SceneDesc("hpd3", "X2", "HP", "2F", "hpd3"),
    new SilentHill3SceneDesc("hpe2", "X2", "HP", "2F", "hpe2", /*hasTr=*/true),
    new SilentHill3SceneDesc("hpe3", "X2", "HP", "2F", "hpe3"),
    new SilentHill3SceneDesc("hpf2", "X2", "HP", "2F", "hpf2"),
    "Brookhaven Hospital - 3F",
    new SilentHill3SceneDesc("hp14", "X2", "HP", "3F", "hp14"),
    new SilentHill3SceneDesc("hp21", "X2", "HP", "3F", "hp21"),
    new SilentHill3SceneDesc("hp21_22_23_24", "X2", "HP", "3F", "hp21_22_23_24"),
    new SilentHill3SceneDesc("hp22", "X2", "HP", "3F", "hp22"),
    new SilentHill3SceneDesc("hp23", "X2", "HP", "3F", "hp23"),
    new SilentHill3SceneDesc("hp24", "X2", "HP", "3F", "hp24"),
    new SilentHill3SceneDesc("hp34", "X2", "HP", "3F", "hp34", /*hasTr=*/true),
    new SilentHill3SceneDesc("hp41", "X2", "HP", "3F", "hp41", /*hasTr=*/true),
    new SilentHill3SceneDesc("hp41_42_43_44", "X2", "HP", "3F", "hp41_42_43_44"),
    new SilentHill3SceneDesc("hp44", "X2", "HP", "3F", "hp44", /*hasTr=*/true),
    new SilentHill3SceneDesc("hp53", "X2", "HP", "3F", "hp53", /*hasTr=*/true),
    new SilentHill3SceneDesc("hp53_54_55_56", "X2", "HP", "3F", "hp53_54_55_56"),
    "Brookhaven Hospital - BF",
    new SilentHill3SceneDesc("hp1e", "X2", "HP", "BF", "hp1e", /*hasTr=*/true),
    new SilentHill3SceneDesc("hp1f", "X2", "HP", "BF", "hp1f", /*hasTr=*/true),
    new SilentHill3SceneDesc("hp2f", "X2", "HP", "BF", "hp2f"),
    new SilentHill3SceneDesc("hpdf", "X2", "HP", "BF", "hpdf"),
    new SilentHill3SceneDesc("hped", "X2", "HP", "BF", "hped"),
    "Brookhaven Hospital (Turning)",
    new SilentHill3SceneDesc("hc1f", "X2", "HC", "", "hc1f"),
    new SilentHill3SceneDesc("hc11", "X2", "HC", "", "hc11"),
    new SilentHill3SceneDesc("hcf1", "X2", "HC", "", "hcf1"),
    new SilentHill3SceneDesc("hcff", "X2", "HC", "", "hcff"),
    "Brookhaven Hospital (Otherworld) - 1F",
    new SilentHill3SceneDesc("hudd", "X2", "HU", "1F", "hudd", /*hasTr=*/true),
    new SilentHill3SceneDesc("hude", "X2", "HU", "1F", "hude"),
    new SilentHill3SceneDesc("hued", "X2", "HU", "1F", "hued"),
    new SilentHill3SceneDesc("huee", "X2", "HU", "1F", "huee"),
    new SilentHill3SceneDesc("huef", "X2", "HU", "1F", "huef (Missing Texture)", /*hasTr=*/true),
    new SilentHill3SceneDesc("hufd", "X2", "HU", "1F", "hufd"),
    new SilentHill3SceneDesc("huff", "X2", "HU", "1F", "huff"),
    "Brookhaven Hospital (Otherworld) - 2F",
    new SilentHill3SceneDesc("hue1", "X2", "HU", "2F", "hue1"),
    new SilentHill3SceneDesc("huf1", "X2", "HU", "2F", "huf1", /*hasTr=*/true),
    new SilentHill3SceneDesc("huf2", "X2", "HU", "2F", "huf2"),
    "Brookhaven Hospital (Otherworld) - 3F",
    new SilentHill3SceneDesc("hu1d", "X2", "HU", "3F", "hu1d", /*hasTr=*/true),
    new SilentHill3SceneDesc("hu1d_nonvertex", "X2", "HU", "3F", "hu1d_nonvertex", /*hasTr=*/true),
    new SilentHill3SceneDesc("hu1f", "X2", "HU", "3F", "hu1f"),
    new SilentHill3SceneDesc("hu2d", "X2", "HU", "3F", "hu2d"),
    new SilentHill3SceneDesc("hu11", "X2", "HU", "3F", "hu11"),
    new SilentHill3SceneDesc("hu12", "X2", "HU", "3F", "hu12"),
    new SilentHill3SceneDesc("hu21", "X2", "HU", "3F", "hu21"),
    new SilentHill3SceneDesc("hu22", "X2", "HU", "3F", "hu22"),
    new SilentHill3SceneDesc("hu31", "X2", "HU", "3F", "hu31"),
    new SilentHill3SceneDesc("hu32", "X2", "HU", "3F", "hu32", /*hasTr=*/true),
    "Lakeside Amusement Park - West",
    new SilentHill3SceneDesc("tp1f", "X3", "TP", "WE", "tp1f"),
    new SilentHill3SceneDesc("tp11", "X3", "TP", "WE", "tp11"),
    new SilentHill3SceneDesc("tpd1", "X3", "TP", "WE", "tpd1"),
    new SilentHill3SceneDesc("tpe1", "X3", "TP", "WE", "tpe1"),
    new SilentHill3SceneDesc("tpf1", "X3", "TP", "WE", "tpf1"),
    new SilentHill3SceneDesc("tpff", "X3", "TP", "WE", "tpff"),
    "Lakeside Amusement Park - South",
    new SilentHill3SceneDesc("tp1d", "X3", "TP", "SO", "tp1d"),
    new SilentHill3SceneDesc("tp1e", "X3", "TP", "SO", "tp1e"),
    new SilentHill3SceneDesc("tp2e", "X3", "TP", "SO", "tp2e"),
    new SilentHill3SceneDesc("tp3d", "X3", "TP", "SO", "tp3d"),
    new SilentHill3SceneDesc("tp3f", "X3", "TP", "SO", "tp3f"),
    new SilentHill3SceneDesc("tpde", "X3", "TP", "SO", "tpde"),
    new SilentHill3SceneDesc("tpdf", "X3", "TP", "SO", "tpdf"),
    new SilentHill3SceneDesc("tpfd", "X3", "TP", "SO", "tpfd"),
    "Lakeside Amusement Park - East",
    new SilentHill3SceneDesc("tp2f", "X3", "TP", "EA", "tp2f"),
    new SilentHill3SceneDesc("tp12", "X3", "TP", "EA", "tp12"),
    new SilentHill3SceneDesc("tp13", "X3", "TP", "EA", "tp13"),
    new SilentHill3SceneDesc("tp21", "X3", "TP", "EA", "tp21"),
    new SilentHill3SceneDesc("tp22", "X3", "TP", "EA", "tp22"),
    new SilentHill3SceneDesc("tp23", "X3", "TP", "EA", "tp23"),
    new SilentHill3SceneDesc("tp31", "X3", "TP", "EA", "tp31"),
    new SilentHill3SceneDesc("tp33", "X3", "TP", "EA", "tp33"),
    new SilentHill3SceneDesc("tpd3", "X3", "TP", "EA", "tpd3"),
    new SilentHill3SceneDesc("tpe2", "X3", "TP", "EA", "tpe2"),
    new SilentHill3SceneDesc("tpe3", "X3", "TP", "EA", "tpe3"),
    new SilentHill3SceneDesc("tpee", "X3", "TP", "EA", "tpee"),
    new SilentHill3SceneDesc("tpef", "X3", "TP", "EA", "tpef"),
    new SilentHill3SceneDesc("tpf2", "X3", "TP", "EA", "tpf2"),
    new SilentHill3SceneDesc("tpf3", "X3", "TP", "EA", "tpf3"),
    new SilentHill3SceneDesc("tpfe", "X3", "TP", "EA", "tpfe"),
    "The Church - Chapel",
    new SilentHill3SceneDesc("cr11", "X3", "CR", "", "cr11"),
    new SilentHill3SceneDesc("cr11_ct", "X3", "CR", "", "cr11_ct"),
    "The Church - Upper",
    new SilentHill3SceneDesc("cu2f", "X3", "CU", "UP", "cu2f"),
    new SilentHill3SceneDesc("cu11", "X3", "CU", "UP", "cu11"),
    new SilentHill3SceneDesc("cu12", "X3", "CU", "UP", "cu12"),
    new SilentHill3SceneDesc("cu21", "X3", "CU", "UP", "cu21"),
    new SilentHill3SceneDesc("cu22", "X3", "CU", "UP", "cu22"),
    new SilentHill3SceneDesc("cud1", "X3", "CU", "UP", "cud1"),
    new SilentHill3SceneDesc("cue1", "X3", "CU", "UP", "cue1"),
    new SilentHill3SceneDesc("cue2", "X3", "CU", "UP", "cue2"),
    new SilentHill3SceneDesc("cuf1", "X3", "CU", "UP", "cuf1"),
    new SilentHill3SceneDesc("cuf2", "X3", "CU", "UP", "cuf2"),
    new SilentHill3SceneDesc("cuf3", "X3", "CU", "UP", "cuf3"),
    new SilentHill3SceneDesc("cufd", "X3", "CU", "UP", "cufd"),
    "The Church - Lower",
    new SilentHill3SceneDesc("cu1d", "X3", "CU", "LOW", "cu1d"),
    new SilentHill3SceneDesc("cu1e", "X3", "CU", "LOW", "cu1e", /*hasTr=*/true),
    new SilentHill3SceneDesc("cu1f", "X3", "CU", "LOW", "cu1f", /*hasTr=*/true),
    new SilentHill3SceneDesc("cu2e", "X3", "CU", "LOW", "cu2e"),
    new SilentHill3SceneDesc("cu3e", "X3", "CU", "LOW", "cu3e"),
    new SilentHill3SceneDesc("cu3f", "X3", "CU", "LOW", "cu3f"),
    new SilentHill3SceneDesc("cu13", "X3", "CU", "LOW", "cu13"),
    new SilentHill3SceneDesc("cu31", "X3", "CU", "LOW", "cu31"),
    new SilentHill3SceneDesc("cudf", "X3", "CU", "LOW", "cudf"),
    new SilentHill3SceneDesc("cuee", "X3", "CU", "LOW", "cuee", /*hasTr=*/true),
    new SilentHill3SceneDesc("cuef", "X3", "CU", "LOW", "cuef"),
    new SilentHill3SceneDesc("cufe", "X3", "CU", "LOW", "cufe"),
    new SilentHill3SceneDesc("cuff", "X3", "CU", "LOW", "cuff"),
    "The Church - Last Room",
    new SilentHill3SceneDesc("cz11", "X3", "CZ", "", "cz11"),
];

export const sceneGroup: Viewer.SceneGroup = { id, name, sceneDescs };
