import * as Viewer from '../viewer';

import { GfxDevice } from '../gfx/platform/GfxPlatform';
import { HauntingGroundRenderer, HauntingGroundTextureHolder } from './render';
import { SceneContext } from '../SceneBase';
import { parseStagePAC } from './pac';

const pathBase = 'HauntingGround';
class HauntingGroundSceneDesc implements Viewer.SceneDesc {
    constructor(public id: string, public name: string = id) {}

    public async createScene(device: GfxDevice, context: SceneContext): Promise<Viewer.SceneGfx> {
        const stageData = await context.dataFetcher.fetchData(`${pathBase}/${this.id}.PAC`);
        const stage = parseStagePAC(stageData);

        const textureHolder = new HauntingGroundTextureHolder;
        textureHolder.addStageTextures(device, stage);

        const renderer = new HauntingGroundRenderer(device, stage, textureHolder);
        return renderer;
    }
}

const id = 'HauntingGround';
const name = 'Haunting Ground';
const sceneDescs = [
    "Castle Belli",
    new HauntingGroundSceneDesc("ST_000", "ST_000"),
    new HauntingGroundSceneDesc("ST_001", "ST_001"),
    new HauntingGroundSceneDesc("ST_002", "ST_002"),
    new HauntingGroundSceneDesc("ST_003", "ST_003"),
    new HauntingGroundSceneDesc("ST_004", "Lunar Refractor Room"),
    new HauntingGroundSceneDesc("ST_005", "Block Puzzle Room (Solved)"),
    new HauntingGroundSceneDesc("ST_006", "Block Puzzle Room"),
    new HauntingGroundSceneDesc("ST_007", "Spiral Stairs"),
    new HauntingGroundSceneDesc("ST_008", "Castle Balcony"),
    new HauntingGroundSceneDesc("ST_009", "Music Room (First Visit)"),
    new HauntingGroundSceneDesc("ST_00A", "Music Room"),
    new HauntingGroundSceneDesc("ST_00B", "Dark Hallway"),
    new HauntingGroundSceneDesc("ST_00C", "Castle Chapel"),
    new HauntingGroundSceneDesc("ST_00D", "ST_00D"),
    new HauntingGroundSceneDesc("ST_00E", "Grand Staircase"),
    new HauntingGroundSceneDesc("ST_00F", "Castle Corridor"),
    new HauntingGroundSceneDesc("ST_010", "East Stairwell"),
    new HauntingGroundSceneDesc("ST_011", "Dining Hall"),
    new HauntingGroundSceneDesc("ST_012", "Kitchen"),
    new HauntingGroundSceneDesc("ST_013", "Garden Stairwell"),
    new HauntingGroundSceneDesc("ST_014", "Bathroom"),
    new HauntingGroundSceneDesc("ST_015", "Marionette Room"),
    new HauntingGroundSceneDesc("ST_016", "Castle Basement"),
    new HauntingGroundSceneDesc("ST_017", "Block Puzzle Room (Cutscene?)"),
    new HauntingGroundSceneDesc("ST_018", "Parlor"),
    new HauntingGroundSceneDesc("ST_019", "Castle Gallery"),
    new HauntingGroundSceneDesc("ST_01A", "Castle Guestroom"),
    new HauntingGroundSceneDesc("ST_01B", "Billiards Room"),
    new HauntingGroundSceneDesc("ST_01C", "Living Room"),
    new HauntingGroundSceneDesc("ST_01D", "Laundry Room"),
    new HauntingGroundSceneDesc("ST_01E", "ST_01E"),
    new HauntingGroundSceneDesc("ST_01F", "ST_01F"),
    new HauntingGroundSceneDesc("ST_020", "Colonnade"),
    new HauntingGroundSceneDesc("ST_021", "Castle Suite"),
    new HauntingGroundSceneDesc("ST_022", "Study"),
    new HauntingGroundSceneDesc("ST_023", "Plate Key Room"),
    new HauntingGroundSceneDesc("ST_024", "Laboratory"),
    new HauntingGroundSceneDesc("ST_025", "ST_025"),
    new HauntingGroundSceneDesc("ST_026", "Nursery"),
    new HauntingGroundSceneDesc("ST_027", "Refining Room"),
    new HauntingGroundSceneDesc("ST_028", "Castle Balcony (Unbroken)"),
    new HauntingGroundSceneDesc("ST_029", "Debilitas' Shack"),
    new HauntingGroundSceneDesc("ST_02A", "ST_02A"),
    new HauntingGroundSceneDesc("ST_02B", "ST_02B"),
    new HauntingGroundSceneDesc("ST_02C", "ST_02C"),
    new HauntingGroundSceneDesc("ST_02D", "Training Ground"),
    new HauntingGroundSceneDesc("ST_02E", "ST_02E"),
    new HauntingGroundSceneDesc("ST_02F", "Castle Drawbridge"),
    new HauntingGroundSceneDesc("ST_030", "Castle Balcony (Drawbridge)"),
    new HauntingGroundSceneDesc("ST_031", "Castle Suite"),
    new HauntingGroundSceneDesc("ST_032", "Castle Suite (Broken Window)"),
    new HauntingGroundSceneDesc("ST_033", "Castle Suite (Tu Fui, Ego Eris)"),
    new HauntingGroundSceneDesc("ST_034", "Cage (Tu Fui, Ego Eris)"),
    new HauntingGroundSceneDesc("ST_035", "Castle Gate (Ending)"),
    new HauntingGroundSceneDesc("ST_036", "Castle Garden (Ending)"),
    new HauntingGroundSceneDesc("ST_037", "Secret Room"),
    "Old Mansion",
    new HauntingGroundSceneDesc("ST_040", "Mansion Entrance"),
    new HauntingGroundSceneDesc("ST_041", "ST_041"),
    new HauntingGroundSceneDesc("ST_042", "Homunculus Room"),
    new HauntingGroundSceneDesc("ST_043", "Cemetary"),
    new HauntingGroundSceneDesc("ST_044", "Mansion Staircase"),
    new HauntingGroundSceneDesc("ST_045", "ST_045"),
    new HauntingGroundSceneDesc("ST_046", "ST_046"),
    new HauntingGroundSceneDesc("ST_047", "Extractor"),
    new HauntingGroundSceneDesc("ST_048", "Cemetary"),
    new HauntingGroundSceneDesc("ST_049", "Mansion Bathroom"),
    new HauntingGroundSceneDesc("ST_04A", "Purifier Room"),
    new HauntingGroundSceneDesc("ST_04B", "ST_04B"),
    new HauntingGroundSceneDesc("ST_04C", "Torture Chamber"),
    new HauntingGroundSceneDesc("ST_04D", "Carousel"),
    new HauntingGroundSceneDesc("ST_04E", "ST_04E"),
    new HauntingGroundSceneDesc("ST_04F", "Dragon Room"),
    new HauntingGroundSceneDesc("ST_050", "Room of Truth"),
    new HauntingGroundSceneDesc("ST_051", "Room of Truth (Lie)"),
    new HauntingGroundSceneDesc("ST_052", "Greenhouse"),
    new HauntingGroundSceneDesc("ST_053", "Projector Room"),
    new HauntingGroundSceneDesc("ST_054", "Mansion Library"),
    new HauntingGroundSceneDesc("ST_055", "Water Chamber"),
    new HauntingGroundSceneDesc("ST_056", "Decomposer Room"),
    new HauntingGroundSceneDesc("ST_057", "Purifier Room"),
    new HauntingGroundSceneDesc("ST_058", "Red Hallway"),
    new HauntingGroundSceneDesc("ST_059", "Medical Room"),
    new HauntingGroundSceneDesc("ST_05B", "ST_05B"),
    new HauntingGroundSceneDesc("ST_05C", "ST_05C"),
    new HauntingGroundSceneDesc("ST_05D", "ST_05D"),
    new HauntingGroundSceneDesc("ST_05E", "Mammoth Passageway"),
    new HauntingGroundSceneDesc("ST_05F", "ST_05F"),
    new HauntingGroundSceneDesc("ST_060", "Mirror Room"),
    new HauntingGroundSceneDesc("ST_061", "ST_061"),
    new HauntingGroundSceneDesc("ST_062", "Mansion Study"),
    new HauntingGroundSceneDesc("ST_063", "Crossbow Puzzle Room"),
    new HauntingGroundSceneDesc("ST_066", "Crypt"),
    new HauntingGroundSceneDesc("ST_067", "Chaos Forest Entrance"),
    new HauntingGroundSceneDesc("ST_068", "Carousel (Revisit)"),
    new HauntingGroundSceneDesc("ST_069", "Synthesizer Room"),
    new HauntingGroundSceneDesc("ST_06A", "ST_06A"),
    new HauntingGroundSceneDesc("ST_06B", "ST_06B"),
    new HauntingGroundSceneDesc("ST_06C", "ST_06C"),
    new HauntingGroundSceneDesc("ST_06D", "ST_06D"),
    new HauntingGroundSceneDesc("ST_06E", "Mansion Colonnade"),
    new HauntingGroundSceneDesc("ST_06F", "ST_06F"),
    new HauntingGroundSceneDesc("ST_070", "Storage Room"),
    "House of Truth",
    new HauntingGroundSceneDesc("ST_080", "Bridge"),
    new HauntingGroundSceneDesc("ST_081", "ST_081"),
    new HauntingGroundSceneDesc("ST_082", "ST_082"),
    new HauntingGroundSceneDesc("ST_083", "ST_083"),
    new HauntingGroundSceneDesc("ST_084", "ST_084"),
    new HauntingGroundSceneDesc("ST_085", "ST_085"),
    new HauntingGroundSceneDesc("ST_086", "ST_086"),
    new HauntingGroundSceneDesc("ST_087", "ST_087"),
    new HauntingGroundSceneDesc("ST_088", "ST_088"),
    new HauntingGroundSceneDesc("ST_08A", "ST_08A"),
    new HauntingGroundSceneDesc("ST_08C", "Conveyor Belt Room"),
    new HauntingGroundSceneDesc("ST_08D", "ST_08D"),
    new HauntingGroundSceneDesc("ST_08E", "ST_08E"),
    new HauntingGroundSceneDesc("ST_08F", "ST_08F"),
    new HauntingGroundSceneDesc("ST_091", "ST_091"),
    new HauntingGroundSceneDesc("ST_092", "Caduceus Room"),
    new HauntingGroundSceneDesc("ST_093", "Color Passageway (Red)"),
    new HauntingGroundSceneDesc("ST_094", "Color Passageway (White)"),
    new HauntingGroundSceneDesc("ST_095", "Color Passageway (Yellow)"),
    new HauntingGroundSceneDesc("ST_096", "Color Passageway (Green)"),
    new HauntingGroundSceneDesc("ST_097", "ST_097"),
    new HauntingGroundSceneDesc("ST_098", "ST_098"),
    new HauntingGroundSceneDesc("ST_099", "ST_099"),
    new HauntingGroundSceneDesc("ST_09A", "ST_09A"),
    new HauntingGroundSceneDesc("ST_09B", "ST_09B"),
    "Water Tower",
    new HauntingGroundSceneDesc("ST_0C0", "Tower Cavern"),
    new HauntingGroundSceneDesc("ST_0C1", "ST_0C1"),
    new HauntingGroundSceneDesc("ST_0C2", "Tower Shaft 1"),
    new HauntingGroundSceneDesc("ST_0C3", "Tower Shaft 2"),
    new HauntingGroundSceneDesc("ST_0C5", "Planetarium"),
    new HauntingGroundSceneDesc("ST_0C6", "Planetarium (Solved)"),
    new HauntingGroundSceneDesc("ST_0C7", "Tower Roof"),
    new HauntingGroundSceneDesc("ST_0C8", "ST_0C8"),
    "Chaos Forest",
    new HauntingGroundSceneDesc("ST_0D0", "ST_0D0"),
    new HauntingGroundSceneDesc("ST_0D1", "ST_0D1"),
    new HauntingGroundSceneDesc("ST_0D2", "ST_0D2"),
    new HauntingGroundSceneDesc("ST_0D3", "ST_0D3"),
    new HauntingGroundSceneDesc("ST_0D4", "ST_0D4"),
    new HauntingGroundSceneDesc("ST_0D5", "ST_0D5"),
    new HauntingGroundSceneDesc("ST_0D6", "ST_0D6"),
    new HauntingGroundSceneDesc("ST_0D7", "ST_0D7"),
    new HauntingGroundSceneDesc("ST_0D8", "ST_0D8"),
    new HauntingGroundSceneDesc("ST_0D9", "ST_0D9"),
    "Minigame: Castle",
    new HauntingGroundSceneDesc("ST_0E0", "ST_0E0"),
    new HauntingGroundSceneDesc("ST_0E1", "ST_0E1"),
    new HauntingGroundSceneDesc("ST_0E2", "ST_0E2"),
    new HauntingGroundSceneDesc("ST_0E3", "ST_0E3"),
    new HauntingGroundSceneDesc("ST_0E4", "ST_0E4"),
    new HauntingGroundSceneDesc("ST_0E5", "ST_0E5"),
    new HauntingGroundSceneDesc("ST_0E6", "ST_0E6"),
    new HauntingGroundSceneDesc("ST_0E7", "ST_0E7"),
    new HauntingGroundSceneDesc("ST_0E8", "ST_0E8"),
    new HauntingGroundSceneDesc("ST_0E9", "ST_0E9"),
    "Minigame: Forest",
    new HauntingGroundSceneDesc("ST_100", "ST_100"),
    new HauntingGroundSceneDesc("ST_101", "ST_101"),
    new HauntingGroundSceneDesc("ST_102", "ST_102"),
    new HauntingGroundSceneDesc("ST_103", "ST_103"),
    new HauntingGroundSceneDesc("ST_104", "ST_104"),
    new HauntingGroundSceneDesc("ST_105", "ST_105"),
    new HauntingGroundSceneDesc("ST_106", "ST_106"),
    new HauntingGroundSceneDesc("ST_107", "ST_107"),
    new HauntingGroundSceneDesc("ST_108", "ST_108"),
    new HauntingGroundSceneDesc("ST_109", "ST_109"),
    new HauntingGroundSceneDesc("ST_10A", "ST_10A"),
    new HauntingGroundSceneDesc("ST_10B", "ST_10B"),
];

export const sceneGroup: Viewer.SceneGroup = { id, name, sceneDescs };
